"""IR → production-grade PySpark code.

Pipeline:
  1. Run the 3-stage optimizer (structural / expression / write).
  2. Emit a tuned ``SparkSession`` (AQE, skew, Kryo, Parquet, STRICT
     assignment policy, …) via ``spark_config.build_session_code``.
  3. Walk IR in topo order, dispatching each node to its plugin.
  4. Wrap fan-out nodes with ``.persist(StorageLevel.X)`` (level chosen
     by W3) and emit ``.unpersist()`` after the last consumer.
  5. Produce an ``OptimizationReport`` that callers can persist + show.
"""
from __future__ import annotations

import textwrap

from ..components import REGISTRY  # triggers plugin discovery
from ..components.base import EmitContext
from ..ir.models import IRNode
from .optimizer import optimize
from .rules.base import OptimizationReport
from .spark_config import build_session_code

_HEADER_PREAMBLE = '''\
"""Generated by Ab Initio → PySpark Conversion Platform."""
import argparse
from functools import reduce

from pyspark import StorageLevel
from pyspark.sql import SparkSession, Window, functions as F
from pyspark.sql.types import (
    StringType, IntegerType, LongType, DoubleType, FloatType,
    BooleanType, DecimalType, DateType, TimestampType,
    ArrayType, StructType, StructField, BinaryType,
)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input",  help="optional override for first read")
    parser.add_argument("--output", help="optional override for last write")
    args = parser.parse_args()

'''

_FOOTER = '''\
    spark.stop()


if __name__ == "__main__":
    main()
'''


def generate_pyspark(
    ir_nodes: list[IRNode],
    app_name: str = "pipeline",
    *,
    return_report: bool = False,
    shuffle_partitions: str = "200",
    broadcast_threshold_mb: int = 10,
):
    """Optimize and render PySpark.

    If ``return_report=True`` returns ``(source, OptimizationReport)``;
    otherwise just the source string (back-compat with v1 callers).
    """
    optimized, report = optimize(ir_nodes, pipeline_id=app_name)
    pretty_app_name = _pick_app_name(optimized, fallback=app_name)
    dop = _resolve_dop(optimized)

    ctx = EmitContext(
        pipeline_id=app_name,
        params=optimized[0].params if optimized else {},
        inputs_by_port={n.id: dict(n.port_inputs) for n in optimized},
        fan_out={n.id: n.fan_out for n in optimized},
    )

    # Schedule unpersists after the last-consumer node body.
    unpersist_after: dict[str, list[str]] = {}
    for n in optimized:
        if n.config.get("cache") and n.config.get("unpersist_after"):
            unpersist_after.setdefault(n.config["unpersist_after"], []).append(n.id)

    body_blocks: list[str] = []
    for node in optimized:
        plugin = REGISTRY.get(node.component_type)
        if plugin is None:
            body_blocks.append(
                f"# [skip] no plugin for {node.component_type!r} ({node.name})"
            )
            continue
        block = plugin.emit_pyspark(node, ctx)
        if not block:
            continue
        if node.config.get("cache"):
            level = node.config.get("storage_level", "MEMORY_AND_DISK")
            var = ctx.df_var(node.id)
            block += (
                f"\n{var} = {var}.persist(StorageLevel.{level})  "
                f"# fan-out × {node.fan_out}, "
                f"unpersist after {node.config.get('unpersist_after')}"
            )
        body_blocks.append(block)
        if node.id in unpersist_after:
            for cached_id in unpersist_after[node.id]:
                body_blocks.append(f"{ctx.df_var(cached_id)}.unpersist()")

    body = "\n\n".join(body_blocks).rstrip() + "\n"
    indented_body = textwrap.indent(body, "    ")
    indented_session = textwrap.indent(
        build_session_code(
            pretty_app_name,
            dop=dop,
            shuffle_partitions=shuffle_partitions,
            broadcast_threshold_mb=broadcast_threshold_mb,
        ),
        "    ",
    )

    src = _HEADER_PREAMBLE + indented_session + "\n" + indented_body + _FOOTER
    if return_report:
        return src, report
    return src


def _pick_app_name(ir_nodes: list[IRNode], fallback: str) -> str:
    if not fallback or _looks_like_uuid(fallback):
        for n in ir_nodes:
            for key in ("PIPELINE_NAME", "pipeline_name", "name"):
                v = n.params.get(key) if isinstance(n.params, dict) else None
                if v:
                    return str(v)
    return fallback


def _looks_like_uuid(s: str) -> bool:
    return len(s) >= 12 and all(c in "0123456789abcdef" for c in s.lower())


def _resolve_dop(ir_nodes: list[IRNode]) -> int:
    for n in ir_nodes:
        raw = (n.params or {}).get("DOP")
        if raw is not None:
            try:
                v = int(raw)
                if v > 0:
                    return v
            except (TypeError, ValueError):
                pass
    return 4
